ServerTokens Prod
ServerSignature Off
ServerName localhost

<Directory /var/www/html>
    Options -Indexes +FollowSymLinks
    AllowOverride None
    Require all denied
</Directory>

<Directory /var/www/html/public_html>
    Options -Indexes +FollowSymLinks
    AllowOverride All
    Require all granted
</Directory>

<FilesMatch "^\.">
    Require all denied
</FilesMatch>
